spring:
  application:
    name: AIOps-demo

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9090/receive-spans
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO

  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","logger":"%c","message":"%m","application":"AIOps-demo"}%n'
    file:    '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","logger":"%c","message":"%m","application":"AIOps-demo"}%n'

  file:
    name: logs/aiops.log
